### ISSUE TITLE
s3 integrator  gets stuck in maintenance status after the pod is evicted

### ISSUE THREAD

**Issue by gtato** [canonical/s3-integrator#44]
## Steps to reproduce

1. The pod gets evicted by K8S and when moved to a different node, the charm gets stuck in maintenance status
2. Deleting the pod does not take it out of that state

## Expected behavior
The integrator goes to an active/idle state

## Actual behavior

![image](https://github.com/user-attachments/assets/c61e9802-4b15-46e2-9500-e053cdc111fe)

K8S events
![image](https://github.com/user-attachments/assets/8a1c7a7d-e36b-431f-b6b1-56361cce782e)

juju status log
![image](https://github.com/user-attachments/assets/e6ee5e47-22cf-4470-9837-51866246630d)

## Versions

Operating system: 

Juju CLI: 

Juju agent: 

Charm revision: 

## Log output

Juju debug log:

**Comment by dragomirp** [comment]
`latest/edge` (revs. 35, 36) should reset the status.
